[
    {
        "Id": "A1",
        "Icon": "",
        "Code": "M-bae22c5c-746e-49cf-aa2f-bbb5cf14afd1",
        "Answer": "Rome",
        "IsAnswer": false,
        "Column": 1,
        "ContentDecode": "",
        "Suggestion": "",
        "Url": "",
        "MimeType": "",
        "Parent": "",
        "Type": "",
        "FileName": "",
        "JsonCanvas": ""
    },
    {
        "Id": "A2",
        "Icon": "",
        "Code": "M-bf5e7358-2c6e-4f2e-9d48-21b03556677c",
        "Answer": "26",
        "IsAnswer": false,
        "Column": 1,
        "ContentDecode": "",
        "Suggestion": "",
        "Url": "",
        "MimeType": "",
        "Parent": "",
        "Type": "",
        "FileName": "",
        "JsonCanvas": ""
    },
    {
        "Id": "A3",
        "Icon": "",
        "Code": "M-01e41672-e7e4-4344-a01d-2ba8885c6e57",
        "Answer": "2001",
        "IsAnswer": false,
        "Column": 1,
        "ContentDecode": "",
        "Suggestion": "",
        "Url": "",
        "MimeType": "",
        "Parent": "",
        "Type": "",
        "FileName": "",
        "JsonCanvas": ""
    },
    {
        "Id": "A4",
        "Icon": "",
        "Code": "M-4c997d39-eb8d-4376-a93b-dc58bc317f06",
        "Answer": "catering",
        "IsAnswer": false,
        "Column": 1,
        "ContentDecode": "",
        "Suggestion": "",
        "Url": "",
        "MimeType": "",
        "Parent": "",
        "Type": "",
        "FileName": "",
        "JsonCanvas": ""
    },
    {
        "Id": "A5",
        "Icon": "",
        "Code": "M-79007420-e520-4c0a-b0a4-18776af62b84",
        "Answer": "south america",
        "IsAnswer": false,
        "Column": 1,
        "ContentDecode": "",
        "Suggestion": "",
        "Url": "",
        "MimeType": "",
        "Parent": "",
        "Type": "",
        "FileName": "",
        "JsonCanvas": ""
    },
    {
        "Id": "A6",
        "Icon": "",
        "Code": "M-c814c695-b7b4-4c90-bf3b-8db8c1677f71",
        "Answer": "bradford",
        "IsAnswer": false,
        "Column": 1,
        "ContentDecode": "",
        "Suggestion": "",
        "Url": "",
        "MimeType": "",
        "Parent": "",
        "Type": "",
        "FileName": "",
        "JsonCanvas": ""
    },
    {
        "Id": "A7",
        "Icon": "",
        "Code": "M-1725d344-2833-4c8c-9dc4-815b432c1016",
        "Answer": "sales",
        "IsAnswer": false,
        "Column": 1,
        "ContentDecode": "",
        "Suggestion": "",
        "Url": "",
        "MimeType": "",
        "Parent": "",
        "Type": "",
        "FileName": "",
        "JsonCanvas": ""
    },
    {
        "Id": "A8",
        "Icon": "",
        "Code": "M-644f6283-cfe4-4f7f-ab2c-f090dcb0950a",
        "Answer": "italian",
        "IsAnswer": false,
        "Column": 1,
        "ContentDecode": "",
        "Suggestion": "",
        "Url": "",
        "MimeType": "",
        "Parent": "",
        "Type": "",
        "FileName": "",
        "JsonCanvas": ""
    },
    {
        "Id": "A9",
        "Icon": "",
        "Code": "M-fcaa0338-b72b-40b7-a354-ae17201a84ef",
        "Answer": "spanish",
        "IsAnswer": false,
        "Column": 1,
        "ContentDecode": "",
        "Suggestion": "",
        "Url": "",
        "MimeType": "",
        "Parent": "",
        "Type": "",
        "FileName": "",
        "JsonCanvas": ""
    },
    {
        "Id": "A10",
        "Icon": "",
        "Code": "M-3564ae56-f7b6-4164-946a-ad5bed47c894",
        "Answer": "7",
        "IsAnswer": false,
        "Column": 1,
        "ContentDecode": "",
        "Suggestion": "",
        "Url": "",
        "MimeType": "",
        "Parent": "",
        "Type": "",
        "FileName": "",
        "JsonCanvas": ""
    }
]
